name: plasmabio-template-bash
channels:
  - conda-forge
dependencies:
  - jupyterlab=2
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
  - simplegeneric # for some reasons needed by rpy2
  - plink=1.90b6.12
  - pip:
    - bash_kernel

